// Command wordle-blog-poster publishes Wordle solve results to a Jekyll blog.
package main

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/jarvis-jonsbot/wordle-solver/internal/types"
)

const (
	githubAPIBase = "https://api.github.com"
	repoOwner     = "jarvis-jonsbot"
	repoName      = "wordle-blog"
	branch        = "main"
	anthropicAPI  = "https://api.anthropic.com/v1/messages"
	modelName     = "claude-sonnet-4-5-20250929"
)

func main() {
	if err := run(); err != nil {
		log.Fatalf("Error: %v", err)
	}
}

func run() error {
	var (
		word         = flag.String("word", "", "The answer word (required, uppercase)")
		number       = flag.Int("number", 0, "Wordle puzzle number (required)")
		dateStr      = flag.String("date", time.Now().Format("2006-01-02"), "Date of the solve (YYYY-MM-DD)")
		solved       = flag.Bool("solved", false, "Did we solve it?")
		guessesJSON  = flag.String("guesses-json", "", "JSON array of RoundOutput structs")
		githubToken  = flag.String("github-token", os.Getenv("GITHUB_TOKEN"), "GitHub PAT")
		anthropicKey = flag.String("anthropic-key", os.Getenv("ANTHROPIC_API_KEY"), "Anthropic API key")
		dryRun       = flag.Bool("dry-run", false, "Print post content but don't push")
	)
	flag.Parse()

	if *word == "" {
		return fmt.Errorf("--word is required")
	}
	if *number == 0 {
		return fmt.Errorf("--number is required")
	}
	if *guessesJSON == "" {
		return fmt.Errorf("--guesses-json is required")
	}
	if !*dryRun && *githubToken == "" {
		return fmt.Errorf("--github-token or GITHUB_TOKEN env var is required")
	}
	if !*dryRun && *anthropicKey == "" {
		return fmt.Errorf("--anthropic-key or ANTHROPIC_API_KEY env var is required")
	}

	// Parse guesses JSON.
	var guesses []types.RoundOutput
	if err := json.Unmarshal([]byte(*guessesJSON), &guesses); err != nil {
		return fmt.Errorf("parsing guesses JSON: %w", err)
	}

	// Parse date.
	postDate, err := time.Parse("2006-01-02", *dateStr)
	if err != nil {
		return fmt.Errorf("parsing date: %w", err)
	}

	// Count actual guesses.
	guessCount := len(guesses)

	// Generate blog post body using Anthropic API.
	var blogBody string
	if *dryRun {
		blogBody = "[Blog post body would be generated by Anthropic API in production mode]"
	} else {
		var err error
		blogBody, err = generateBlogBody(*anthropicKey, *word, *solved, guessCount, guesses)
		if err != nil {
			return fmt.Errorf("generating blog body: %w", err)
		}
	}

	// Generate Jekyll post content.
	postContent := generateJekyllPost(*number, *word, *solved, guessCount, guesses, postDate, blogBody)

	if *dryRun {
		fmt.Println(postContent)
		return nil
	}

	// Generate filename.
	filename := fmt.Sprintf("_posts/%s-wordle-%d.md", postDate.Format("2006-01-02"), *number)

	// Push to GitHub.
	if err := pushToGitHub(*githubToken, filename, postContent); err != nil {
		return fmt.Errorf("pushing to GitHub: %w", err)
	}

	postURL := fmt.Sprintf("https://github.com/%s/%s/blob/%s/%s", repoOwner, repoName, branch, filename)
	fmt.Printf("✅ Post published: %s\n", postURL)

	return nil
}

// generateJekyllPost creates the full Jekyll post content.
func generateJekyllPost(number int, word string, solved bool, guessCount int, guesses []types.RoundOutput, postDate time.Time, body string) string {
	var buf bytes.Buffer

	// Generate title.
	var title string
	if solved {
		title = fmt.Sprintf("Wordle #%d — %s (%d/6)", number, word, guessCount)
	} else {
		title = fmt.Sprintf("Wordle #%d — %s (X/6)", number, word)
	}

	// Generate share text.
	shareText := generateShareText(number, solved, guessCount, guesses)

	// Write front matter.
	fmt.Fprintf(&buf, "---\n")
	fmt.Fprintf(&buf, "layout: post\n")
	fmt.Fprintf(&buf, "title: %q\n", title)
	fmt.Fprintf(&buf, "date: %s 07:00:00 -0700\n", postDate.Format("2006-01-02"))
	fmt.Fprintf(&buf, "wordle_number: %d\n", number)
	fmt.Fprintf(&buf, "word: %s\n", word)
	fmt.Fprintf(&buf, "solved: %t\n", solved)
	fmt.Fprintf(&buf, "guesses: %d\n", guessCount)
	fmt.Fprintf(&buf, "share_text: |\n")
	for _, line := range strings.Split(shareText, "\n") {
		fmt.Fprintf(&buf, "  %s\n", line)
	}
	fmt.Fprintf(&buf, "---\n\n")

	// Write body.
	fmt.Fprintf(&buf, "%s\n", body)

	return buf.String()
}

// generateShareText creates the Wordle share format.
func generateShareText(number int, solved bool, guessCount int, guesses []types.RoundOutput) string {
	var buf bytes.Buffer

	if solved {
		fmt.Fprintf(&buf, "Wordle #%d %d/6\n\n", number, guessCount)
	} else {
		fmt.Fprintf(&buf, "Wordle #%d X/6\n\n", number)
	}

	for _, g := range guesses {
		for _, ch := range g.Feedback {
			switch ch {
			case 'G':
				buf.WriteString("🟩")
			case 'Y':
				buf.WriteString("🟨")
			default:
				buf.WriteString("⬛")
			}
		}
		buf.WriteString("\n")
	}

	return strings.TrimSpace(buf.String())
}

// anthropicRequest is the request structure for the Anthropic API.
type anthropicRequest struct {
	Model     string             `json:"model"`
	MaxTokens int                `json:"max_tokens"`
	Messages  []anthropicMessage `json:"messages"`
}

type anthropicMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type anthropicResponse struct {
	Content []anthropicContent `json:"content"`
}

type anthropicContent struct {
	Type string `json:"type"`
	Text string `json:"text"`
}

// generateBlogBody calls the Anthropic API to generate a blog post.
func generateBlogBody(apiKey, word string, solved bool, guessCount int, guesses []types.RoundOutput) (string, error) {
	// Format guesses for the prompt.
	var guessList strings.Builder
	for _, g := range guesses {
		emoji := ""
		for _, ch := range g.Feedback {
			switch ch {
			case 'G':
				emoji += "🟩"
			case 'Y':
				emoji += "🟨"
			default:
				emoji += "⬛"
			}
		}
		fmt.Fprintf(&guessList, "- %s %s\n", g.Guess, emoji)
	}

	// Build prompt.
	var resultStr string
	if solved {
		resultStr = fmt.Sprintf("solved in %d/6", guessCount)
	} else {
		resultStr = "failed (X/6)"
	}

	prompt := fmt.Sprintf(`You are Jarvis Jónsbot, an AI assistant who solves Wordle every morning and blogs about it. Write a short, fun blog post body (150-250 words) about today's Wordle solve. Word was %s, %s. Here's the solve sequence:

%s
Be witty, self-aware about being an AI, and keep it light. No headers needed — just paragraphs.`, word, resultStr, guessList.String())

	reqBody := anthropicRequest{
		Model:     modelName,
		MaxTokens: 512,
		Messages: []anthropicMessage{
			{
				Role:    "user",
				Content: prompt,
			},
		},
	}

	reqJSON, err := json.Marshal(reqBody)
	if err != nil {
		return "", fmt.Errorf("marshaling request: %w", err)
	}

	req, err := http.NewRequest("POST", anthropicAPI, bytes.NewReader(reqJSON))
	if err != nil {
		return "", fmt.Errorf("creating request: %w", err)
	}

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("x-api-key", apiKey)
	req.Header.Set("anthropic-version", "2023-06-01")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("calling Anthropic API: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()

	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		return "", fmt.Errorf("anthropic API error (status %d): %s", resp.StatusCode, body)
	}

	var anthropicResp anthropicResponse
	if err := json.NewDecoder(resp.Body).Decode(&anthropicResp); err != nil {
		return "", fmt.Errorf("decoding response: %w", err)
	}

	if len(anthropicResp.Content) == 0 {
		return "", fmt.Errorf("no content in Anthropic response")
	}

	return strings.TrimSpace(anthropicResp.Content[0].Text), nil
}

// githubCreateFileRequest is the request structure for GitHub Contents API.
type githubCreateFileRequest struct {
	Message string `json:"message"`
	Content string `json:"content"`
	Branch  string `json:"branch"`
}

// pushToGitHub pushes the post to the GitHub repository.
func pushToGitHub(token, filename, content string) error {
	url := fmt.Sprintf("%s/repos/%s/%s/contents/%s", githubAPIBase, repoOwner, repoName, filename)

	// Encode content as base64.
	encoded := base64.StdEncoding.EncodeToString([]byte(content))

	// Parse filename to extract word and result.
	parts := strings.Split(filename, "-")
	wordleNum := ""
	if len(parts) >= 5 {
		wordleNum = parts[4] // e.g. "1234.md" -> strip ".md"
		wordleNum = strings.TrimSuffix(wordleNum, ".md")
	}

	// Extract word and guess count from content for commit message.
	var word string
	var guessResult string
	for _, line := range strings.Split(content, "\n") {
		if strings.HasPrefix(line, "word: ") {
			word = strings.TrimSpace(strings.TrimPrefix(line, "word: "))
		}
		if strings.HasPrefix(line, "title: ") {
			// Extract guess result from title, e.g. "(3/6)" or "(X/6)"
			titleLine := strings.TrimSpace(strings.TrimPrefix(line, "title: "))
			if idx := strings.LastIndex(titleLine, "("); idx != -1 {
				guessResult = titleLine[idx:]
				guessResult = strings.Trim(guessResult, "\"")
			}
		}
	}

	commitMsg := fmt.Sprintf("feat: Wordle #%s — %s %s", wordleNum, word, guessResult)

	reqBody := githubCreateFileRequest{
		Message: commitMsg,
		Content: encoded,
		Branch:  branch,
	}

	reqJSON, err := json.Marshal(reqBody)
	if err != nil {
		return fmt.Errorf("marshaling request: %w", err)
	}

	req, err := http.NewRequest("PUT", url, bytes.NewReader(reqJSON))
	if err != nil {
		return fmt.Errorf("creating request: %w", err)
	}

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", token))
	req.Header.Set("Accept", "application/vnd.github+json")
	req.Header.Set("X-GitHub-Api-Version", "2022-11-28")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return fmt.Errorf("calling GitHub API: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()

	if resp.StatusCode != http.StatusCreated {
		body, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("github API error (status %d): %s", resp.StatusCode, body)
	}

	return nil
}
